image: bcgovimages/von-image:py36-1.8-0

Agent Tests:
  stage: test
  script:
    - mkdir test-reports
    - mkdir test-reports/pytest
    - cd agent
    - python3 -m venv venv
    - . venv/bin/activate
    - pip install -r requirements.txt -r requirements.dev.txt pytest
    - pytest
    - ls -last
    - pwd
  coverage: '/^TOTAL\s+\d+\s+\d+\s+(\d+\%)$/'
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - test-reports/
    reports:
      junit: test-reports/pytest/junit.xml
    expire_in: 1 week

# Dependency Scanning
include:
  template: Dependency-Scanning.gitlab-ci.yml

# Code Quality Scanning
code_quality:
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --env SOURCE_CODE="$PWD"
        --volume "$PWD":/code
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /code
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
    expire_in: 1 week

pages:
  stage: deploy
  dependencies:
    - Agent Tests
  script:
    - mkdir public
    - cp -r test-reports/cov_html/* public
  artifacts:
    paths:
      - public
    expire_in: 1 week